#!/usr/bin/env bash
# =============================================================================
# Phase 1 security cutover — one-shot server prep.
#
# Run this ON THE DROPLET *before* deploying main-with-Phase-1. It:
#   1. generates secrets and writes the off-repo env file (/opt/civil-registry/.env.production)
#   2. backs up Postgres + Mongo
#   3. provisions the least-privilege civil_app Postgres role
#   4. creates the Mongo root + civil_app users
#
# It does NOT rotate any credential the *currently running* app uses, so the live
# app keeps working until you redeploy — no downtime window. Idempotent: re-running
# reuses the existing env file.
#
# Easiest invocation (pipe this file straight to the droplet from your machine):
#   ssh root@134.209.105.170 'bash -s' < deploy/phase1-cutover.sh
#
# Then:  merge phase1-security-cutover into main and `git push origin main`.
# =============================================================================
set -euo pipefail

APP_DIR="$HOME/apps/AdvanceDatabase_Project"
COMPOSE="docker compose -f docker-compose.prod.yml"
ENV_DIR="/opt/civil-registry"
ENV_FILE="$ENV_DIR/.env.production"

cd "$APP_DIR"

# Strong, shell/JSON/SQL-safe secret (alphanumeric only).
gen() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c 32; }

# --- 1. Secrets + env file -------------------------------------------------
if [ -f "$ENV_FILE" ]; then
  echo "==> $ENV_FILE already exists — reusing it."
  set -a; . "$ENV_FILE"; set +a
else
  echo "==> Generating secrets and writing $ENV_FILE"
  APP_KEY="base64:$(openssl rand -base64 32)"
  DB_PASSWORD="$(gen)"
  MONGO_INITDB_ROOT_PASSWORD="$(gen)"
  MONGO_PASSWORD="$(gen)"
  mkdir -p "$ENV_DIR"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/phase1-cutover.sh on $(date -u +%FT%TZ). Keep secret.
APP_KEY=$APP_KEY
# Postgres superuser: kept as-is (loopback-only; only migrate.sh uses it). The
# app itself connects as the least-privilege civil_app role below.
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
DB_USERNAME=civil_app
DB_PASSWORD=$DB_PASSWORD
MONGO_INITDB_ROOT_USERNAME=root
MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
MONGO_USERNAME=civil_app
MONGO_PASSWORD=$MONGO_PASSWORD
EOF
  chmod 600 "$ENV_FILE"
fi

# --- 2. Backups ------------------------------------------------------------
STAMP="$(date +%Y%m%d-%H%M%S)"
echo "==> Backing up Postgres → ~/pre-phase1-pg-$STAMP.sql.gz"
$COMPOSE exec -T postgres pg_dump -U postgres civil_registry | gzip > "$HOME/pre-phase1-pg-$STAMP.sql.gz"
echo "==> Backing up Mongo → ~/pre-phase1-mongo-$STAMP.archive.gz"
$COMPOSE exec -T mongo mongodump --quiet --archive | gzip > "$HOME/pre-phase1-mongo-$STAMP.archive.gz"

# --- 3. Provision civil_app Postgres role ----------------------------------
echo "==> Provisioning civil_app Postgres role"
$COMPOSE exec -T postgres psql -v ON_ERROR_STOP=1 -U postgres -d civil_registry \
  -v civil_app_pw="$DB_PASSWORD" <<'SQL'
SELECT NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'civil_app') AS create_role \gset
\if :create_role
  CREATE ROLE civil_app LOGIN PASSWORD :'civil_app_pw';
\else
  ALTER ROLE civil_app LOGIN PASSWORD :'civil_app_pw';
\endif
GRANT CONNECT ON DATABASE civil_registry TO civil_app;
GRANT USAGE ON SCHEMA public TO civil_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO civil_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO civil_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO civil_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO civil_app;
REVOKE CREATE ON SCHEMA public FROM civil_app;
SQL

# --- 4. Provision Mongo users (mongo still runs without --auth here) --------
echo "==> Provisioning Mongo root + civil_app users"
$COMPOSE exec -T mongo mongosh --quiet <<EOF
const admin = db.getSiblingDB('admin');
if (admin.getUser('root')) admin.updateUser('root', { pwd: '${MONGO_INITDB_ROOT_PASSWORD}', roles: ['root'] });
else admin.createUser({ user: 'root', pwd: '${MONGO_INITDB_ROOT_PASSWORD}', roles: ['root'] });
const appdb = db.getSiblingDB('civil_registry_docs');
const roles = [{ role: 'readWrite', db: 'civil_registry_docs' }];
if (appdb.getUser('civil_app')) appdb.updateUser('civil_app', { pwd: '${MONGO_PASSWORD}', roles });
else appdb.createUser({ user: 'civil_app', pwd: '${MONGO_PASSWORD}', roles });
print('mongo users ready');
EOF

echo
echo "✅ Phase 1 cutover prep complete."
echo "   Next: merge phase1-security-cutover into main, then 'git push origin main'."
echo "   The APP_KEY was rotated; the old committed key is now dead."
